timezone: America/Sao_Paulo
ntp_servers:
  - "ntp.ubuntu.com
  - pool.ntp.org
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
  - a.st1.ntp.br
  - b.st1.ntp.br
  - c.st1.ntp.br
  - a.ntp.br
  - b.ntp.br
  - c.ntp.br
  - pool.ntp.org
ping_host: 8.8.8.8
last_sync_file: .cache/last_sync_date.log