timezone: America/Sao_Paulo
ntp_servers:
  - a.st1.ntp.br
  - b.st1.ntp.br
  - c.st1.ntp.br
  - a.ntp.br
  - b.ntp.br
  - c.ntp.br
  - pool.ntp.org
ping_host: 8.8.8.8
last_sync_file: .cache/last_sync_date.log